### PR TITLE
added support for symfony7

### PR DESCRIPTION
**Pull request by fmarquesto**
Added support for Symfony 7 and added missing return on a test

### CODE REVIEW

**Comment by Daniel-Marynicz** [comment]
Please remove  needs: quality 
from .github/workflows/php.yml
and add to matrix symfony 7.0

**Comment by fmarquesto** [comment]
@Daniel-Marynicz done ✅

**Comment by Daniel-Marynicz** [comment]
please remove from the matrix `ubuntu-18.04` (github removed ubuntu 18.04) and fill the CHANGELOG.md with new version 1.0.3.

And after this i will merge and release version 1.0.3. Thank you.

**Comment by fmarquesto** [comment]
✅

**Comment by Daniel-Marynicz** [comment]
Thank you.

**Pull request merged**
